---
web_instance_type: t2.micro

web_security_groups:
  - sg_name: "{{ vpc_name }}-web-sg"
    sg_description: This sg is for app instance
    sg_rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    # sg_rules_egress:


# Use a pre-prepared EC2 instance with Wordpress installed and running
web_ami_id: ami-79119e0a
